/* auto-generated by genmsg_cpp from /home/gaitt/Work_CCNY/pkgs/ccny-ros-pkg/ccny_vision/ar_pose/msg/ARMarker.msg.  Do not edit! */
#ifndef AR_POSE_ARMARKER_H
#define AR_POSE_ARMARKER_H

#include <string>
#include <vector>
#include "ros/message.h"
#include "ros/debug.h"
#include "ros/assert.h"
#include "ros/time.h"

#include "roslib/Header.h"
#include "geometry_msgs/Point.h"
#include "geometry_msgs/Quaternion.h"
#include "geometry_msgs/Pose.h"
#include "geometry_msgs/PoseWithCovariance.h"

namespace ar_pose
{

//! \htmlinclude ARMarker.msg.html

class ARMarker : public ros::Message
{
public:
  typedef boost::shared_ptr<ARMarker> Ptr;
  typedef boost::shared_ptr<ARMarker const> ConstPtr;

  typedef roslib::Header _header_type;
  typedef uint32_t _id_type;
  typedef geometry_msgs::PoseWithCovariance _pose_type;
  typedef uint32_t _confidence_type;

  roslib::Header header;
  uint32_t id;
  geometry_msgs::PoseWithCovariance pose;
  uint32_t confidence;

  ARMarker() : ros::Message(),
    id(0),
    confidence(0)
  {
  }
  ARMarker(const ARMarker &copy) : ros::Message(),
    header(copy.header),
    id(copy.id),
    pose(copy.pose),
    confidence(copy.confidence)
  {
    (void)copy;
  }
  ARMarker &operator =(const ARMarker &copy)
  {
    if (this == &copy)
      return *this;
    header = copy.header;
    id = copy.id;
    pose = copy.pose;
    confidence = copy.confidence;
    return *this;
  }
  virtual ~ARMarker() 
  {
  }
  inline static std::string __s_getDataType() { return std::string("ar_pose/ARMarker"); }
  inline static std::string __s_getMD5Sum() { return std::string("93c4ce9061a70bc30293e52ac4675f76"); }
  inline static std::string __s_getMessageDefinition()
  {
    return std::string(
    "Header header\n"
    "uint32 id\n"
    "geometry_msgs/PoseWithCovariance pose\n"
    "uint32 confidence\n"
    "\n"
    "================================================================================\n"
    "MSG: roslib/Header\n"
    "# Standard metadata for higher-level stamped data types.\n"
    "# This is generally used to communicate timestamped data \n"
    "# in a particular coordinate frame.\n"
    "# \n"
    "# sequence ID: consecutively increasing ID \n"
    "uint32 seq\n"
    "#Two-integer timestamp that is expressed as:\n"
    "# * stamp.secs: seconds (stamp_secs) since epoch\n"
    "# * stamp.nsecs: nanoseconds since stamp_secs\n"
    "# time-handling sugar is provided by the client library\n"
    "time stamp\n"
    "#Frame this data is associated with\n"
    "# 0: no frame\n"
    "# 1: global frame\n"
    "string frame_id\n"
    "\n"
    "================================================================================\n"
    "MSG: geometry_msgs/PoseWithCovariance\n"
    "# This represents a pose in free space with uncertainty.\n"
    "\n"
    "Pose pose\n"
    "\n"
    "# Row-major representation of the 6x6 covariance matrix\n"
    "# The orientation parameters use a fixed-axis representation.\n"
    "# In order, the parameters are:\n"
    "# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
    "float64[36] covariance\n"
    "\n"
    "================================================================================\n"
    "MSG: geometry_msgs/Pose\n"
    "# A representation of pose in free space, composed of postion and orientation. \n"
    "Point position\n"
    "Quaternion orientation\n"
    "\n"
    "================================================================================\n"
    "MSG: geometry_msgs/Point\n"
    "# This contains the position of a point in free space\n"
    "float64 x\n"
    "float64 y\n"
    "float64 z\n"
    "\n"
    "================================================================================\n"
    "MSG: geometry_msgs/Quaternion\n"
    "# This represents an orientation in free space in quaternion form.\n"
    "\n"
    "float64 x\n"
    "float64 y\n"
    "float64 z\n"
    "float64 w\n"
    "\n"
    "\n"
    );
  }
  inline virtual const std::string __getDataType() const { return __s_getDataType(); }
  inline virtual const std::string __getMD5Sum() const { return __s_getMD5Sum(); }
  inline virtual const std::string __getMessageDefinition() const { return __s_getMessageDefinition(); }
  inline uint32_t serializationLength() const
  {
    unsigned __l = 0;
    __l += header.serializationLength(); // header
    __l += 4; // id
    __l += pose.serializationLength(); // pose
    __l += 4; // confidence
    return __l;
  }
  virtual uint8_t *serialize(uint8_t *write_ptr,
                             uint32_t seq) const
  {
    roslib::Header _ser_header = header;
    bool __reset_seq = (header.seq == 0);
    if (__reset_seq) _ser_header.seq = seq;
    write_ptr = _ser_header.serialize(write_ptr, seq);
    SROS_SERIALIZE_PRIMITIVE(write_ptr, id);
    write_ptr = pose.serialize(write_ptr, seq);
    SROS_SERIALIZE_PRIMITIVE(write_ptr, confidence);
    return write_ptr;
  }
  virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    read_ptr = header.deserialize(read_ptr);
    SROS_DESERIALIZE_PRIMITIVE(read_ptr, id);
    read_ptr = pose.deserialize(read_ptr);
    SROS_DESERIALIZE_PRIMITIVE(read_ptr, confidence);
    return read_ptr;
  }
};

typedef boost::shared_ptr<ARMarker> ARMarkerPtr;
typedef boost::shared_ptr<ARMarker const> ARMarkerConstPtr;


}

#endif
